# Jekyll configuration

name: 电解质的鸡窝
description: 

# Url is currently only used only for the RSS feed in feed.xml
url: https://hawksjamesf.github.io
# url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/blog'
asseturl: '/blog/asset'

share:
  facebook: true
  twitter: true
  # gplus: true
  linkedin: true
  # pinterest: true
  email: true

social:
  github: HawksJamesf
  stackoverflow: '6393208/hawks93jf'
  linkedin:
  # instagram: ''
  # lastfm: ''
  rss: feed.xml
  zhihu: 'wei-zhi-end'
  weibo: 'weizhiend'
  douban: 'weizhiend'
  

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: HawksJamesf
comments: true 

permalink: /:year-:month-:day/:title
# permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

highlighter: rouge
# highlighter: pygments
# pygments: true

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
encoding: utf-8
timezone: Asia/Shanghai
future: true
date_formater: "%a, %b %d %Y, %R"
